// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdnamwvouzmnmklxethj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbmFtd3ZvdXptbm1rbHhldGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODU5NjMsImV4cCI6MjA2OTE2MTk2M30.BkwUGgzlzwhv0R5Yakhh88QSOGOmddQSpqUCR8oOKAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});